### ISSUE TITLE
TypeError: density() missing 1 required positional argument: 'cond'

### ISSUE THREAD

**Issue by leaf-fucker** [Zielon/INSTA-pytorch#5]
Traceback (most recent call last):
  File "/INSTA-pytorch/main_insta.py", line 132, in <module>
    trainer.save_mesh(resolution=256, threshold=10)
  File "/INSTA-pytorch/insta/utils.py", line 602, in save_mesh
    vertices, triangles = extract_geometry(self.model.aabb_infer[:3], self.model.aabb_infer[3:], resolution=resolution, threshold=threshold, query_func=query_func)
  File "/INSTA-pytorch/insta/utils.py", line 182, in extract_geometry
    u = extract_fields(bound_min, bound_max, resolution, query_func)
  File "/INSTA-pytorch/insta/utils.py", line 175, in extract_fields
    val = query_func(pts).reshape(len(xs), len(ys), len(zs)).detach().cpu().numpy()  # [S, 1] --> [x, y, z]
  File "/INSTA-pytorch/insta/utils.py", line 599, in query_func
    sigma = self.model.density(pts.to(self.device))['sigma']
TypeError: density() missing 1 required positional argument: 'cond'

**Comment by fasogbon** [comment]
Any solution please?

**Comment by fyyakaxyy** [comment]
> Traceback (most recent call last): File "/INSTA-pytorch/main_insta.py", line 132, in trainer.save_mesh(resolution=256, threshold=10) File "/INSTA-pytorch/insta/utils.py", line 602, in save_mesh vertices, triangles = extract_geometry(self.model.aabb_infer[:3], self.model.aabb_infer[3:], resolution=resolution, threshold=threshold, query_func=query_func) File "/INSTA-pytorch/insta/utils.py", line 182, in extract_geometry u = extract_fields(bound_min, bound_max, resolution, query_func) File "/INSTA-pytorch/insta/utils.py", line 175, in extract_fields val = query_func(pts).reshape(len(xs), len(ys), len(zs)).detach().cpu().numpy() # [S, 1] --> [x, y, z] File "/INSTA-pytorch/insta/utils.py", line 599, in query_func sigma = self.model.density(pts.to(self.device))['sigma'] TypeError: density() missing 1 required positional argument: 'cond'

me too
